axis_types:
- [z, z, z, z, z, z]
collision_file_name: collision_ur3e.yaml
collision_nn_file: ur3e_nn
disp_offsets:
- [0.0, 0.0, 0.151591275663]
displacements:
- - [-9.32783264461e-05, 0.0, 0.0]
  - [-0.243746325923, 0.0, 0.0]
  - [-0.212946558354, -0.000983354710539, 0.13109426355]
  - [9.13566112809e-05, -0.0853218541233, -0.000127686520102]
  - [-0.000204644187552, 0.0919106284329, -0.000101802119305]
  - [0.0, 0.0, 0.0]
ee_fixed_joints: [ee_fixed_joint]
fixed_frame: base_link
fixed_frame_noise_scale: 0.0
fixed_frame_noise_frequency: 1
joint_limits:
- [-6.28318530718, 6.28318530718]
- [-6.28318530718, 6.28318530718]
- [-3.14159265359, 3.14159265359]
- [-6.28318530718, 6.28318530718]
- [-6.28318530718, 6.28318530718]
- [-6.28318530718, 6.28318530718]
joint_names:
- [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint,
  wrist_3_joint]
joint_ordering: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint,
  wrist_2_joint, wrist_3_joint]
joint_state_define_func_file: ur3e_joint_state_define
joint_types:
- [revolute, revolute, revolute, revolute, revolute, revolute]
mode: absolute
objectives:
- type: position
  index: 1
  weight: 30.0
  gradient: forward_ad
- type: rotation
  index: 1
  weight: 2.0
  gradient: forward_ad
- type: positional_noise
  index: 1
  scale: 0.15
  weight: 0.0
  gradient: forward_ad
  frequency: 4.0
- type: rotational_noise
  index: 1
  scale: 1.0
  weight: 0.0
  gradient: forward_ad
  frequency: 4.0
- type: dc
  index: 2
  weight: 0.0
  gradient: forward_ad
# - type: dc_noise
#   index: 1
#   scale: 0.5371884221
#   weight: 0.0
#   gradient: forward_ad
#   frequency: 4
- type: dc_noise
  index: 2
  scale: 0.52807446068
  weight: 3.0
  gradient: forward_ad
  frequency: 4.0
# - type: dc_noise
#   index: 3
#   scale: 0.71847205049
#   weight: 0.0
#   gradient: forward_ad
#   frequency: 4
# - type: dc_noise
#   index: 4
#   scale: 0.59641281529
#   weight: 0.0
#   gradient: forward_ad
#   frequency: 4
# - type: dc_noise
#   index: 5
#   scale: 0.39374551588
#   weight: 0.0
#   gradient: forward_ad
#   frequency: 4
# - type: dc_noise
#   index: 6
#   scale: 0.45956975793
#   weight: 0.0
#   gradient: forward_ad
#   frequency: 4
- type: min_jt_vel
  weight: 5.0
  gradient: forward_ad
- type: min_jt_accel
  weight: 2.0
  gradient: forward_ad
- type: min_jt_jerk
  weight: 0.1
  gradient: forward_ad
- type: joint_limit
  weight: 1.0
  gradient: forward_ad
- type: collision_nn
  weight: 5.0
  gradient: finite_diff
# path_to_src: /vagrant/src/lively_ik/src
rot_offsets:
- - [0.0, 0.0, 3.14159297124]
  - [1.57008236343, 0.0, 9.72792840537e-06]
  - [3.13889669648, 3.1394450528, 3.14157553155]
  - [0.00750098624527, 0.000417023234307, 1.5779934395e-05]
  - [1.5722928534, 0.0, 5.41797589164e-06]
  - [1.5696887065, 3.14159265359, 3.1415923227]
  - [0.0, -1.57079632679, 1.57079632679]
starting_config: [1.55, -1.77, 1.4, -1.19, -1.57, 0.0]
urdf_file_name: ur3e.urdf
velocity_limits: [3.14, 3.14, 3.14, 6.28, 6.28, 6.28]
