axis_types:
- [z, y]
- [y, z, x, z, x, x]
- [y, z, x, z, x, x]
- [-z, x, y, y, y, x]
- [z, x, y, y, y, x]
collision_file_name: collision_nao_v4.yaml
collision_nn_file: nao_v5_nn
disp_offsets:
- [0.0, 0.0, 0.1265]
- [0.0, 0.098, 0.1]
- [0.0, -0.098, 0.1]
- [0.0, 0.05, -0.085]
- [0.0, -0.05, -0.085]
displacements:
- - [0.0, 0.0, 0.0]
  - [0.05871, 0.0, 0.06364]
- - [0.0, 0.0, 0.0]
  - [0.105, 0.015, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.05595, 0.0, 0.0]
  - [0.05775, 0.0, -0.01231]
  - [0.0, 0.0, 0.0]
- - [0.0, 0.0, 0.0]
  - [0.105, -0.015, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.05595, 0.0, 0.0]
  - [0.05775, 0.0, -0.01213]
  - [0.0, 0.0, 0.0]
- - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, -0.1]
  - [0.0, 0.0, -0.1029]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, -0.04511]
- - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, -0.1]
  - [0.0, 0.0, -0.1029]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, -0.04511]
ee_fixed_joints: [gaze_joint, LArm_effector_fixedjoint, RArm_effector_fixedjoint,
  LLeg_effector_fixedjoint, RLeg_effector_fixedjoint]
fixed_frame: base_link
fixed_frame_noise_scale: 0.02
fixed_frame_noise_frequency: 6
mode: absolute
objectives:
  - type: position   # Position Objectives
    index: 1
    weight: 1.0
    gradient: forward_ad
  - type: position
    index: 2
    weight: 6.0
    gradient: forward_ad
  - type: position
    index: 3
    weight: 6.0
    gradient: forward_ad
  - type: position
    index: 4
    weight: 4.0
    gradient: forward_ad
  - type: position
    index: 5
    weight: 4.0
    gradient: forward_ad
  - type: rotation   # Rotation Objectives
    index: 1
    weight: 1.0
    gradient: forward_ad
  - type: rotation
    index: 2
    weight: 4.0
    gradient: forward_ad
  - type: rotation
    index: 3
    weight: 4.0
    gradient: forward_ad
  - type: rotation
    index: 4
    weight: 5.0
    gradient: forward_ad
  - type: rotation
    index: 5
    weight: 5.0
    gradient: forward_ad
  - type: positional_noise  # Position Noise Objectives
    index: 2
    scale: 0.008
    weight: 5.0
    gradient: forward_ad
    frequency: 4.0
  - type: positional_noise
    index: 3
    scale: 0.008
    weight: 5.0
    gradient: forward_ad
    frequency: 4.0
  - type: rotational_noise  # Rotation Noise Objectives
    index: 1 # Head
    scale: 0.004
    weight: 0.5
    gradient: forward_ad
    frequency: 4.0
  - type: rotational_noise
    index: 2 # Arm 1
    scale: 0.003
    weight: 0.5
    gradient: forward_ad
    frequency: 4.0
  - type: rotational_noise
    index: 3  # Arm 2
    scale: 0.003
    weight: 0.5
    gradient: forward_ad
    frequency: 4.0
  - type: dc_noise
    index: 25
    scale: 0.25
    weight: 5.0
    gradient: forward_ad
    frequency: 4
  - type: dc_noise
    index: 26
    scale: 0.25
    weight: 5.0
    gradient: forward_ad
    frequency: 4
  - type: min_jt_vel
    weight: 5.0
    gradient: forward_ad
  - type: min_jt_accel
    weight: 2.0
    gradient: forward_ad
  - type: min_jt_jerk
    weight: 0.1
    gradient: forward_ad
  - type: joint_limit
    weight: 1.0
    gradient: forward_ad
  - type: collision_nn
    weight: 5.0
    gradient: finite_diff
  - type: "x_match_position"
    delta: 0
    index_1: 4
    index_2: 5
    weight: 5
    gradient: forward_ad
  - type: "z_match_position"
    delta: 0
    index_1: 4
    index_2: 5
    weight: 5
    gradient: forward_ad
joint_limits:
- [-2.08567, 2.08567]
- [-0.671952, 0.514872]
- [-2.08567, 2.08567]
- [-0.314159, 1.32645]
- [-2.08567, 2.08567]
- [-1.54462, -0.0349066]
- [-1.82387, 1.82387]
- [-2.08567, 2.08567]
- [-1.32645, 0.314159]
- [-2.08567, 2.08567]
- [0.0349066, 1.54462]
- [-1.82387, 1.82387]
- [-1.14529, 0.740718]
- [-0.379435, 0.79046]
- [-1.53589, 0.48398]
- [-0.0923279, 2.11255]
- [-1.18944, 0.922581]
- [-0.397761, 0.768992]
- [-1.14529, 0.740718]
- [-0.79046, 0.379435]
- [-1.53589, 0.48398]
- [-0.0923279, 2.11255]
- [-1.1863, 0.932006]
- [-0.768992, 0.397761]
- [0.0, 1.0]
- [0.0, 1.0]
joint_names:
- [HeadYaw, HeadPitch]
- [LShoulderPitch, LShoulderRoll, LElbowYaw, LElbowRoll, LWristYaw, LHand]
- [RShoulderPitch, RShoulderRoll, RElbowYaw, RElbowRoll, RWristYaw, RHand]
- [LHipYawPitch, LHipRoll, LHipPitch, LKneePitch, LAnklePitch, LAnkleRoll]
- [RHipYawPitch, RHipRoll, RHipPitch, RKneePitch, RAnklePitch, RAnkleRoll]
joint_ordering: [HeadYaw, HeadPitch, LShoulderPitch, LShoulderRoll, LElbowYaw, LElbowRoll,
  LWristYaw, RShoulderPitch, RShoulderRoll, RElbowYaw, RElbowRoll, RWristYaw, LHipYawPitch,
  LHipRoll, LHipPitch, LKneePitch, LAnklePitch, LAnkleRoll, RHipYawPitch, RHipRoll,
  RHipPitch, RKneePitch, RAnklePitch, RAnkleRoll, LHand, RHand]
joint_state_define_func_file: nao_v5_joint_state_define
joint_types:
- [revolute, revolute]
- [revolute, revolute, revolute, revolute, revolute, revolute]
- [revolute, revolute, revolute, revolute, revolute, revolute]
- [revolute, revolute, revolute, revolute, revolute, revolute]
- [revolute, revolute, revolute, revolute, revolute, revolute]
match_objectives: []
path_to_src: /vagrant/src/lively_ik/src
rot_offsets:
- - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
- - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
- - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
- - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
- - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
starting_config: [0, 0, 1.5, 0.15, 0, -0.04, -1.3, 1.5, -0.15, 0, 0.04, 1.3, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.4, 0.4]
urdf_file_name: nao_v5.urdf
velocity_limits: [8.26797, 7.19407, 8.26797, 7.19407, 8.26797, 7.19407, 24.6229, 8.26797,
  7.19407, 8.26797, 7.19407, 24.6229, 4.16174, 4.16174, 6.40239, 6.40239, 6.40239,
  4.16174, 4.16174, 4.16174, 6.40239, 6.40239, 6.40239, 4.16174, 8.33, 8.33]
