all_dynamic_joints:
- panda_joint1
- panda_joint2
- panda_joint3
- panda_joint4
- panda_joint5
- panda_joint6
- panda_joint7
- panda_finger_joint1
- panda_finger_joint2
all_fixed_joints:
- panda_joint8
- panda_hand_joint
all_links:
- panda_link0
- panda_link1
- panda_link2
- panda_link3
- panda_link4
- panda_link5
- panda_link6
- panda_link7
- panda_link8
- panda_hand
- panda_leftfinger
- panda_rightfinger
axis_types:
- - z
  - z
  - z
  - z
  - z
  - z
  - z
boxes:
- coordinate_frame: 0
  name: Box 1
  parameters:
  - 3
  - 3
  - 0.05
  rotation:
  - 0
  - 0
  - 0
  translation:
  - 0
  - 0
  - 0
capsules: []
cylinders: []
disp_offsets:
- - 0.0
  - 0.0
  - 0.333
displacements:
- - - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - -0.316
    - 0.0
  - - 0.0825
    - 0.0
    - 0.0
  - - -0.0825
    - 0.384
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
  - - 0.088
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.107
ee_fixed_joints:
- panda_joint8
ellipsoids: []
fixed_frame: panda_link0
fixed_frame_noise_frequency: 0
fixed_frame_noise_scale: 0
joint_limits:
- - -2.9671
  - 2.9671
- - -1.8326
  - 1.8326
- - -2.9671
  - 2.9671
- - -3.1416
  - 0.0873
- - -2.9671
  - 2.9671
- - -0.0873
  - 3.8223
- - -2.9671
  - 2.9671
- - 0.0
  - 0.04
- - 0.0
  - 0.04
joint_names:
- - panda_joint1
  - panda_joint2
  - panda_joint3
  - panda_joint4
  - panda_joint5
  - panda_joint6
  - panda_joint7
joint_ordering:
- panda_joint1
- panda_joint2
- panda_joint3
- panda_joint4
- panda_joint5
- panda_joint6
- panda_joint7
- panda_finger_joint1
- panda_finger_joint2
joint_types:
- - revolute
  - revolute
  - revolute
  - revolute
  - revolute
  - revolute
  - revolute
js_define: "from sensor_msgs.msg import JointState\ndef joint_state_define(x):\n\t\
  return None\n"
mode: absolute
objectives:
- gradient: forward_ad
  index: 1
  type: position
  weight: 50
- gradient: forward_ad
  type: collision_nn
  weight: 3
problem_states:
- - -0.33
  - 1.03
  - 0
  - -3.04
  - 0
  - 1.8675
  - 0
  - 0.02
  - 0.02
- - -0.67
  - 1.03
  - 0
  - -3.04
  - 0
  - 1.8675
  - 0
  - 0.02
  - 0.02
robot_link_radius: 0.05
robot_name: panda
rot_offsets:
- - - 0.0
    - 0.0
    - 0.0
  - - -1.57079632679
    - 0.0
    - 0.0
  - - 1.57079632679
    - 0.0
    - 0.0
  - - 1.57079632679
    - 0.0
    - 0.0
  - - -1.57079632679
    - 0.0
    - 0.0
  - - 1.57079632679
    - 0.0
    - 0.0
  - - 1.57079632679
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
sample_states:
- - 0
  - 0
  - 0
  - -1.52715
  - 0
  - 1.8675
  - 0
  - 0.02
  - 0.02
- - 1.08
  - -0.01
  - 0
  - -1.71
  - 0
  - 1.8675
  - 0
  - 0.02
  - 0.02
spheres: []
starting_config:
- 0.0
- 0.0
- 0.0
- -1.52715
- 0.0
- 1.8675
- 0.0
- 0.02
- 0.02
training_states:
- - 0
  - 0
  - 0
  - -1.52715
  - 0
  - 1.8675
  - 0
  - 0.02
  - 0.02
- - -1.74
  - -0.05
  - 0
  - -1.71
  - 0
  - 1.8675
  - 0
  - 0.02
  - 0.02
urdf: "<?xml version=\"1.0\" ?>\n<!-- ===================================================================================\
  \ -->\n<!-- |    This document was autogenerated by xacro from /opt/ros/kinetic/share/moveit_resources/panda_description/urdf/panda.urdf\
  \ | -->\n<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                \
  \                 | -->\n<!-- ===================================================================================\
  \ -->\n<robot name=\"panda\" xmlns:xacro=\"http://www.ros.org/wiki/xacro\">\n  \
  \  <link name=\"panda_link0\">\n        <visual>\n            <geometry>\n     \
  \           <mesh filename=\"package://moveit_resources_panda_description/meshes/visual/link0.dae\"\
  \ />\n            </geometry>\n        </visual>\n        <collision>\n        \
  \    <geometry>\n                <mesh filename=\"package://moveit_resources_panda_description/meshes/collision/link0.stl\"\
  \ />\n            </geometry>\n        </collision>\n    </link>\n    <link name=\"\
  panda_link1\">\n        <visual>\n            <geometry>\n                <mesh\
  \ filename=\"package://moveit_resources_panda_description/meshes/visual/link1.dae\"\
  \ />\n            </geometry>\n        </visual>\n        <collision>\n        \
  \    <geometry>\n                <mesh filename=\"package://moveit_resources_panda_description/meshes/collision/link1.stl\"\
  \ />\n            </geometry>\n        </collision>\n    </link>\n    <joint name=\"\
  panda_joint1\" type=\"revolute\">\n        <safety_controller k_position=\"100.0\"\
  \ k_velocity=\"40.0\" soft_lower_limit=\"-2.8973\" soft_upper_limit=\"2.8973\" />\n\
  \        <origin rpy=\"0 0 0\" xyz=\"0 0 0.333\" />\n        <parent link=\"panda_link0\"\
  \ />\n        <child link=\"panda_link1\" />\n        <axis xyz=\"0 0 1\" />\n \
  \       <limit effort=\"87\" lower=\"-2.9671\" upper=\"2.9671\" velocity=\"2.3925\"\
  \ />\n    </joint>\n    <link name=\"panda_link2\">\n        <visual>\n        \
  \    <geometry>\n                <mesh filename=\"package://moveit_resources_panda_description/meshes/visual/link2.dae\"\
  \ />\n            </geometry>\n        </visual>\n        <collision>\n        \
  \    <geometry>\n                <mesh filename=\"package://moveit_resources_panda_description/meshes/collision/link2.stl\"\
  \ />\n            </geometry>\n        </collision>\n    </link>\n    <joint name=\"\
  panda_joint2\" type=\"revolute\">\n        <safety_controller k_position=\"100.0\"\
  \ k_velocity=\"40.0\" soft_lower_limit=\"-1.7628\" soft_upper_limit=\"1.7628\" />\n\
  \        <origin rpy=\"-1.57079632679 0 0\" xyz=\"0 0 0\" />\n        <parent link=\"\
  panda_link1\" />\n        <child link=\"panda_link2\" />\n        <axis xyz=\"0\
  \ 0 1\" />\n        <limit effort=\"87\" lower=\"-1.8326\" upper=\"1.8326\" velocity=\"\
  2.3925\" />\n    </joint>\n    <link name=\"panda_link3\">\n        <visual>\n \
  \           <geometry>\n                <mesh filename=\"package://moveit_resources_panda_description/meshes/visual/link3.dae\"\
  \ />\n            </geometry>\n        </visual>\n        <collision>\n        \
  \    <geometry>\n                <mesh filename=\"package://moveit_resources_panda_description/meshes/collision/link3.stl\"\
  \ />\n            </geometry>\n        </collision>\n    </link>\n    <joint name=\"\
  panda_joint3\" type=\"revolute\">\n        <safety_controller k_position=\"100.0\"\
  \ k_velocity=\"40.0\" soft_lower_limit=\"-2.8973\" soft_upper_limit=\"2.8973\" />\n\
  \        <origin rpy=\"1.57079632679 0 0\" xyz=\"0 -0.316 0\" />\n        <parent\
  \ link=\"panda_link2\" />\n        <child link=\"panda_link3\" />\n        <axis\
  \ xyz=\"0 0 1\" />\n        <limit effort=\"87\" lower=\"-2.9671\" upper=\"2.9671\"\
  \ velocity=\"2.3925\" />\n    </joint>\n    <link name=\"panda_link4\">\n      \
  \  <visual>\n            <geometry>\n                <mesh filename=\"package://moveit_resources_panda_description/meshes/visual/link4.dae\"\
  \ />\n            </geometry>\n        </visual>\n        <collision>\n        \
  \    <geometry>\n                <mesh filename=\"package://moveit_resources_panda_description/meshes/collision/link4.stl\"\
  \ />\n            </geometry>\n        </collision>\n    </link>\n    <joint name=\"\
  panda_joint4\" type=\"revolute\">\n        <safety_controller k_position=\"100.0\"\
  \ k_velocity=\"40.0\" soft_lower_limit=\"-3.0718\" soft_upper_limit=\"0.0175\" />\n\
  \        <origin rpy=\"1.57079632679 0 0\" xyz=\"0.0825 0 0\" />\n        <parent\
  \ link=\"panda_link3\" />\n        <child link=\"panda_link4\" />\n        <axis\
  \ xyz=\"0 0 1\" />\n        <limit effort=\"87\" lower=\"-3.1416\" upper=\"0.0873\"\
  \ velocity=\"2.3925\" />\n    </joint>\n    <link name=\"panda_link5\">\n      \
  \  <visual>\n            <geometry>\n                <mesh filename=\"package://moveit_resources_panda_description/meshes/visual/link5.dae\"\
  \ />\n            </geometry>\n        </visual>\n        <collision>\n        \
  \    <geometry>\n                <mesh filename=\"package://moveit_resources_panda_description/meshes/collision/link5.stl\"\
  \ />\n            </geometry>\n        </collision>\n    </link>\n    <joint name=\"\
  panda_joint5\" type=\"revolute\">\n        <safety_controller k_position=\"100.0\"\
  \ k_velocity=\"40.0\" soft_lower_limit=\"-2.8973\" soft_upper_limit=\"2.8973\" />\n\
  \        <origin rpy=\"-1.57079632679 0 0\" xyz=\"-0.0825 0.384 0\" />\n       \
  \ <parent link=\"panda_link4\" />\n        <child link=\"panda_link5\" />\n    \
  \    <axis xyz=\"0 0 1\" />\n        <limit effort=\"12\" lower=\"-2.9671\" upper=\"\
  2.9671\" velocity=\"2.8710\" />\n    </joint>\n    <link name=\"panda_link6\">\n\
  \        <visual>\n            <geometry>\n                <mesh filename=\"package://moveit_resources_panda_description/meshes/visual/link6.dae\"\
  \ />\n            </geometry>\n        </visual>\n        <collision>\n        \
  \    <geometry>\n                <mesh filename=\"package://moveit_resources_panda_description/meshes/collision/link6.stl\"\
  \ />\n            </geometry>\n        </collision>\n    </link>\n    <joint name=\"\
  panda_joint6\" type=\"revolute\">\n        <safety_controller k_position=\"100.0\"\
  \ k_velocity=\"40.0\" soft_lower_limit=\"-0.0175\" soft_upper_limit=\"3.7525\" />\n\
  \        <origin rpy=\"1.57079632679 0 0\" xyz=\"0 0 0\" />\n        <parent link=\"\
  panda_link5\" />\n        <child link=\"panda_link6\" />\n        <axis xyz=\"0\
  \ 0 1\" />\n        <limit effort=\"12\" lower=\"-0.0873\" upper=\"3.8223\" velocity=\"\
  2.8710\" />\n    </joint>\n    <link name=\"panda_link7\">\n        <visual>\n \
  \           <geometry>\n                <mesh filename=\"package://moveit_resources_panda_description/meshes/visual/link7.dae\"\
  \ />\n            </geometry>\n        </visual>\n        <collision>\n        \
  \    <geometry>\n                <mesh filename=\"package://moveit_resources_panda_description/meshes/collision/link7.stl\"\
  \ />\n            </geometry>\n        </collision>\n    </link>\n    <joint name=\"\
  panda_joint7\" type=\"revolute\">\n        <safety_controller k_position=\"100.0\"\
  \ k_velocity=\"40.0\" soft_lower_limit=\"-2.8973\" soft_upper_limit=\"2.8973\" />\n\
  \        <origin rpy=\"1.57079632679 0 0\" xyz=\"0.088 0 0\" />\n        <parent\
  \ link=\"panda_link6\" />\n        <child link=\"panda_link7\" />\n        <axis\
  \ xyz=\"0 0 1\" />\n        <limit effort=\"12\" lower=\"-2.9671\" upper=\"2.9671\"\
  \ velocity=\"2.8710\" />\n    </joint>\n    <link name=\"panda_link8\" />\n    <joint\
  \ name=\"panda_joint8\" type=\"fixed\">\n        <origin rpy=\"0 0 0\" xyz=\"0 0\
  \ 0.107\" />\n        <parent link=\"panda_link7\" />\n        <child link=\"panda_link8\"\
  \ />\n        <axis xyz=\"0 0 0\" />\n    </joint>\n    <joint name=\"panda_hand_joint\"\
  \ type=\"fixed\">\n        <parent link=\"panda_link8\" />\n        <child link=\"\
  panda_hand\" />\n        <origin rpy=\"0 0 -0.785398163397\" xyz=\"0 0 0\" />\n\
  \    </joint>\n    <link name=\"panda_hand\">\n        <visual>\n            <geometry>\n\
  \                <mesh filename=\"package://moveit_resources_panda_description/meshes/visual/hand.dae\"\
  \ />\n            </geometry>\n        </visual>\n        <collision>\n        \
  \    <geometry>\n                <mesh filename=\"package://moveit_resources_panda_description/meshes/collision/hand.stl\"\
  \ />\n            </geometry>\n        </collision>\n    </link>\n    <link name=\"\
  panda_leftfinger\">\n        <visual>\n            <geometry>\n                <mesh\
  \ filename=\"package://moveit_resources_panda_description/meshes/visual/finger.dae\"\
  \ />\n            </geometry>\n        </visual>\n        <collision>\n        \
  \    <geometry>\n                <mesh filename=\"package://moveit_resources_panda_description/meshes/collision/finger.stl\"\
  \ />\n            </geometry>\n        </collision>\n    </link>\n    <link name=\"\
  panda_rightfinger\">\n        <visual>\n            <origin rpy=\"0 0 3.14159265359\"\
  \ xyz=\"0 0 0\" />\n            <geometry>\n                <mesh filename=\"package://moveit_resources_panda_description/meshes/visual/finger.dae\"\
  \ />\n            </geometry>\n        </visual>\n        <collision>\n        \
  \    <origin rpy=\"0 0 3.14159265359\" xyz=\"0 0 0\" />\n            <geometry>\n\
  \                <mesh filename=\"package://moveit_resources_panda_description/meshes/collision/finger.stl\"\
  \ />\n            </geometry>\n        </collision>\n    </link>\n    <joint name=\"\
  panda_finger_joint1\" type=\"prismatic\">\n        <parent link=\"panda_hand\" />\n\
  \        <child link=\"panda_leftfinger\" />\n        <origin rpy=\"0 0 0\" xyz=\"\
  0 0 0.0584\" />\n        <axis xyz=\"0 1 0\" />\n        <limit effort=\"20\" lower=\"\
  0.0\" upper=\"0.04\" velocity=\"0.2\" />\n    </joint>\n    <joint name=\"panda_finger_joint2\"\
  \ type=\"prismatic\">\n        <parent link=\"panda_hand\" />\n        <child link=\"\
  panda_rightfinger\" />\n        <origin rpy=\"0 0 0\" xyz=\"0 0 0.0584\" />\n  \
  \      <axis xyz=\"0 -1 0\" />\n        <limit effort=\"20\" lower=\"0.0\" upper=\"\
  0.04\" velocity=\"0.2\" />\n        <mimic joint=\"panda_finger_joint1\" />\n  \
  \  </joint>\n</robot>\n"
velocity_limits:
- 2.3925
- 2.3925
- 2.3925
- 2.3925
- 2.871
- 2.871
- 2.871
- 0.2
- 0.2
