all_dynamic_joints:
- shoulder_pan_joint
- shoulder_lift_joint
- elbow_joint
- wrist_1_joint
- wrist_2_joint
- wrist_3_joint
all_fixed_joints:
- ee_fixed_joint
- base_link-base_fixed_joint
- wrist_3_link-tool0_fixed_joint
- world_joint
all_links:
- base_link
- shoulder_link
- upper_arm_link
- forearm_link
- wrist_1_link
- wrist_2_link
- wrist_3_link
- ee_link
- base
- tool0
- world
axis_types:
- - z
  - z
  - z
  - z
  - z
  - z
boxes:
- coordinate_frame: 0
  name: Box 1
  parameters:
  - 3
  - 3
  - 0.3
  rotation:
  - 0
  - 0
  - 0
  translation:
  - 0
  - 0
  - 0
capsules: []
cylinders: []
disp_offsets:
- - 0.0
  - 0.0
  - 0.151591275663
displacements:
- - - -9.32783264461e-05
    - 0.0
    - 0.0
  - - -0.243746325923
    - 0.0
    - 0.0
  - - -0.212946558354
    - -0.000983354710539
    - 0.13109426355
  - - 9.13566112809e-05
    - -0.0853218541233
    - -0.000127686520102
  - - -0.000204644187552
    - 0.0919106284329
    - -0.000101802119305
  - - 0.0
    - 0.0
    - 0.0
ee_fixed_joints:
- ee_fixed_joint
ellipsoids: []
fixed_frame: base_link
fixed_frame_noise_frequency: 0
fixed_frame_noise_scale: 0
joint_limits:
- - -6.28318530718
  - 6.28318530718
- - -6.28318530718
  - 6.28318530718
- - -3.14159265359
  - 3.14159265359
- - -6.28318530718
  - 6.28318530718
- - -6.28318530718
  - 6.28318530718
- - -6.28318530718
  - 6.28318530718
joint_names:
- - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint
joint_ordering:
- shoulder_pan_joint
- shoulder_lift_joint
- elbow_joint
- wrist_1_joint
- wrist_2_joint
- wrist_3_joint
joint_types:
- - revolute
  - revolute
  - revolute
  - revolute
  - revolute
  - revolute
js_define: "from sensor_msgs.msg import JointState\ndef joint_state_define(x):\n\t\
  return None\n"
mode: absolute
objectives:
- gradient: forward_ad
  index: 1
  type: position
  weight: 30
- frequency: 5
  gradient: forward_ad
  index: 1
  scale: 0.15
  type: positional_noise
  weight: 20
- gradient: forward_ad
  index: 1
  type: rotation
  weight: 10
- frequency: 5
  gradient: forward_ad
  index: 1
  scale: 1
  type: rotational_noise
  weight: 5
- gradient: forward_ad
  type: min_jt_vel
  weight: 5
- gradient: forward_ad
  type: min_jt_accel
  weight: 2
- gradient: forward_ad
  type: min_jt_jerk
  weight: 0.1
- gradient: forward_ad
  type: joint_limit
  weight: 1
- gradient: forward_ad
  type: collision_nn
  weight: 5
problem_states:
- - 4.47
  - -0.78
  - -2.7
  - -4.39
  - 0.05
  - 0
- - 4.47
  - -0.78
  - -2.7
  - -4.39
  - -3.88
  - 0
robot_link_radius: 0.05
robot_name: ur3e_simple
rot_offsets:
- - - 0.0
    - 0.0
    - 3.14159297124
  - - 1.57008236343
    - 0.0
    - 9.72792840537e-06
  - - 3.13889669648
    - 3.1394450528
    - 3.14157553155
  - - 0.00750098624527
    - 0.000417023234307
    - 1.5779934395e-05
  - - 1.5722928534
    - 0.0
    - 5.41797589164e-06
  - - 1.5696887065
    - 3.14159265359
    - 3.1415923227
  - - 0.0
    - -1.57079632679
    - 1.57079632679
sample_states:
- - 0
  - -2.4
  - 0.79
  - 0
  - 0.05
  - 0
- - -3.48
  - -2.4
  - 0.79
  - 0
  - 0.05
  - 0
- - 4.47
  - -2.4
  - 0.79
  - 0
  - 0.05
  - 0
spheres: []
starting_config:
- 0
- -2.4
- 0.79
- 0
- 0.05
- 0
training_states:
- - -3.48
  - -2.4
  - 0.79
  - 0
  - 0.05
  - 0
- - 4.47
  - -2.4
  - 0.79
  - 0
  - 0.05
  - 0
- - 4.47
  - -0.78
  - 0.79
  - 0
  - 0.05
  - 0
- - 4.47
  - -0.78
  - 0.79
  - -4.39
  - 0.05
  - 0
urdf: "<?xml version=\"1.0\" ?>\n<!-- ===================================================================================\
  \ -->\n<!-- |    This document was autogenerated by xacro from ./ur3e_robot.urdf.xacro\
  \        | -->\n<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED         \
  \                        | -->\n<!-- ===================================================================================\
  \ -->\n<robot name=\"ur3e\" xmlns:xacro=\"http://ros.org/wiki/xacro\">\n  <gazebo>\n\
  \    <plugin filename=\"libgazebo_ros_control.so\" name=\"ros_control\">\n     \
  \ <!--robotNamespace>/</robotNamespace-->\n      <!--robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType-->\n\
  \    </plugin>\n    <!--\n    <plugin name=\"gazebo_ros_power_monitor_controller\"\
  \ filename=\"libgazebo_ros_power_monitor.so\">\n      <alwaysOn>true</alwaysOn>\n\
  \      <updateRate>1.0</updateRate>\n      <timeout>5</timeout>\n      <powerStateTopic>power_state</powerStateTopic>\n\
  \      <powerStateRate>10.0</powerStateRate>\n      <fullChargeCapacity>87.78</fullChargeCapacity>\n\
  \      <dischargeRate>-474</dischargeRate>\n      <chargeRate>525</chargeRate>\n\
  \      <dischargeVoltage>15.52</dischargeVoltage>\n      <chargeVoltage>16.41</chargeVoltage>\n\
  \    </plugin>\n-->\n  </gazebo>\n  <!--\n  Author: Felix Messmer\n-->\n  <!-- measured\
  \ from model -->\n  <link name=\"base_link\">\n    <visual>\n      <origin rpy=\"\
  0 0 3.14159265359\" xyz=\"0 0 0\"/>\n      <geometry>\n        <mesh filename=\"\
  package://ur_e_description/meshes/ur3e/visual/base.dae\"/>\n      </geometry>\n\
  \      <material name=\"LightGrey\">\n        <color rgba=\"0.7 0.7 0.7 1.0\"/>\n\
  \      </material>\n    </visual>\n    <collision>\n      <origin rpy=\"0 0 3.14159265359\"\
  \ xyz=\"0 0 0\"/>\n      <geometry>\n        <mesh filename=\"package://ur_e_description/meshes/ur3e/collision/base.stl\"\
  />\n      </geometry>\n    </collision>\n    <inertial>\n      <mass value=\"2.0\"\
  />\n      <origin rpy=\"0 0 0\" xyz=\"0.0 0.0 0.0\"/>\n      <inertia ixx=\"0.0030531654454\"\
  \ ixy=\"0.0\" ixz=\"0.0\" iyy=\"0.0030531654454\" iyz=\"0.0\" izz=\"0.005625\"/>\n\
  \    </inertial>\n  </link>\n  <joint name=\"shoulder_pan_joint\" type=\"revolute\"\
  >\n    <parent link=\"base_link\"/>\n    <child link=\"shoulder_link\"/>\n    <origin\
  \ rpy=\"0 0 3.14159297124\" xyz=\"0 0 0.151591275663\"/>\n    <axis xyz=\"0 0 1\"\
  />\n    <limit effort=\"330.0\" lower=\"-6.28318530718\" upper=\"6.28318530718\"\
  \ velocity=\"3.14\"/>\n    <dynamics damping=\"0.0\" friction=\"0.0\"/>\n  </joint>\n\
  \  <link name=\"shoulder_link\">\n    <visual>\n      <origin rpy=\"0 0 3.14159265359\"\
  \ xyz=\"0 0 0\"/>\n      <geometry>\n        <mesh filename=\"package://ur_e_description/meshes/ur3e/visual/shoulder.dae\"\
  />\n      </geometry>\n      <material name=\"LightGrey\">\n        <color rgba=\"\
  0.7 0.7 0.7 1.0\"/>\n      </material>\n    </visual>\n    <collision>\n      <origin\
  \ rpy=\"0 0 3.14159265359\" xyz=\"0 0 0\"/>\n      <geometry>\n        <mesh filename=\"\
  package://ur_e_description/meshes/ur3e/collision/shoulder.stl\"/>\n      </geometry>\n\
  \    </collision>\n    <inertial>\n      <mass value=\"2.0\"/>\n      <origin rpy=\"\
  0 0 0\" xyz=\"0.0 0.0 0.0\"/>\n      <inertia ixx=\"0.0080931634294\" ixy=\"0.0\"\
  \ ixz=\"0.0\" iyy=\"0.0080931634294\" iyz=\"0.0\" izz=\"0.005625\"/>\n    </inertial>\n\
  \  </link>\n  <joint name=\"shoulder_lift_joint\" type=\"revolute\">\n    <parent\
  \ link=\"shoulder_link\"/>\n    <child link=\"upper_arm_link\"/>\n    <origin rpy=\"\
  1.57008236343 0 9.72792840537e-06\" xyz=\"-9.32783264461e-05 0 0\"/>\n    <axis\
  \ xyz=\"0 0 1\"/>\n    <limit effort=\"330.0\" lower=\"-6.28318530718\" upper=\"\
  6.28318530718\" velocity=\"3.14\"/>\n    <dynamics damping=\"0.0\" friction=\"0.0\"\
  />\n  </joint>\n  <link name=\"upper_arm_link\">\n    <visual>\n      <origin rpy=\"\
  1.57079632679 0 -1.57079632679\" xyz=\"0 0 0.12\"/>\n      <geometry>\n        <mesh\
  \ filename=\"package://ur_e_description/meshes/ur3e/visual/upperarm.dae\"/>\n  \
  \    </geometry>\n      <material name=\"LightGrey\">\n        <color rgba=\"0.7\
  \ 0.7 0.7 1.0\"/>\n      </material>\n    </visual>\n    <collision>\n      <origin\
  \ rpy=\"1.57079632679 0 -1.57079632679\" xyz=\"0 0 0.12\"/>\n      <geometry>\n\
  \        <mesh filename=\"package://ur_e_description/meshes/ur3e/collision/upperarm.stl\"\
  />\n      </geometry>\n    </collision>\n    <inertial>\n      <mass value=\"3.42\"\
  />\n      <origin rpy=\"0 1.57079632679 0\" xyz=\"-0.121873162961 0.0 0.12\"/>\n\
  \      <inertia ixx=\"0.0217418636525\" ixy=\"0.0\" ixz=\"0.0\" iyy=\"0.0217418636525\"\
  \ iyz=\"0.0\" izz=\"0.00961875\"/>\n    </inertial>\n  </link>\n  <joint name=\"\
  elbow_joint\" type=\"revolute\">\n    <parent link=\"upper_arm_link\"/>\n    <child\
  \ link=\"forearm_link\"/>\n    <origin rpy=\"3.13889669648 3.1394450528 3.14157553155\"\
  \ xyz=\"-0.243746325923 0 0\"/>\n    <axis xyz=\"0 0 1\"/>\n    <limit effort=\"\
  150.0\" lower=\"-3.14159265359\" upper=\"3.14159265359\" velocity=\"3.14\"/>\n \
  \   <dynamics damping=\"0.0\" friction=\"0.0\"/>\n  </joint>\n  <link name=\"forearm_link\"\
  >\n    <visual>\n      <origin rpy=\"1.57079632679 0 -1.57079632679\" xyz=\"0 0\
  \ 0.027\"/>\n      <geometry>\n        <mesh filename=\"package://ur_e_description/meshes/ur3e/visual/forearm.dae\"\
  />\n      </geometry>\n      <material name=\"LightGrey\">\n        <color rgba=\"\
  0.7 0.7 0.7 1.0\"/>\n      </material>\n    </visual>\n    <collision>\n      <origin\
  \ rpy=\"1.57079632679 0 -1.57079632679\" xyz=\"0 0 0.027\"/>\n      <geometry>\n\
  \        <mesh filename=\"package://ur_e_description/meshes/ur3e/collision/forearm.stl\"\
  />\n      </geometry>\n    </collision>\n    <inertial>\n      <mass value=\"1.26\"\
  />\n      <origin rpy=\"0 1.57079632679 0\" xyz=\"-0.121873162961 0.0 0.027\"/>\n\
  \      <inertia ixx=\"0.00653322724176\" ixy=\"0.0\" ixz=\"0.0\" iyy=\"0.00653322724176\"\
  \ iyz=\"0.0\" izz=\"0.00354375\"/>\n    </inertial>\n  </link>\n  <joint name=\"\
  wrist_1_joint\" type=\"revolute\">\n    <parent link=\"forearm_link\"/>\n    <child\
  \ link=\"wrist_1_link\"/>\n    <origin rpy=\"0.00750098624527 0.000417023234307\
  \ 1.5779934395e-05\" xyz=\"-0.212946558354 -0.000983354710539 0.13109426355\"/>\n\
  \    <axis xyz=\"0 0 1\"/>\n    <limit effort=\"54.0\" lower=\"-6.28318530718\"\
  \ upper=\"6.28318530718\" velocity=\"6.28\"/>\n    <dynamics damping=\"0.0\" friction=\"\
  0.0\"/>\n  </joint>\n  <link name=\"wrist_1_link\">\n    <visual>\n      <origin\
  \ rpy=\"1.57079632679 0 0\" xyz=\"0 0 -0.104\"/>\n      <geometry>\n        <mesh\
  \ filename=\"package://ur_e_description/meshes/ur3e/visual/wrist1.dae\"/>\n    \
  \  </geometry>\n      <material name=\"LightGrey\">\n        <color rgba=\"0.7 0.7\
  \ 0.7 1.0\"/>\n      </material>\n    </visual>\n    <collision>\n      <origin\
  \ rpy=\"1.57079632679 0 0\" xyz=\"0 0 -0.104\"/>\n      <geometry>\n        <mesh\
  \ filename=\"package://ur_e_description/meshes/ur3e/collision/wrist1.stl\"/>\n \
  \     </geometry>\n    </collision>\n    <inertial>\n      <mass value=\"0.8\"/>\n\
  \      <origin rpy=\"0 0 0\" xyz=\"0.0 0.0 0.0\"/>\n      <inertia ixx=\"0.00161032060861\"\
  \ ixy=\"0.0\" ixz=\"0.0\" iyy=\"0.00161032060861\" iyz=\"0.0\" izz=\"0.00225\"/>\n\
  \    </inertial>\n  </link>\n  <joint name=\"wrist_2_joint\" type=\"revolute\">\n\
  \    <parent link=\"wrist_1_link\"/>\n    <child link=\"wrist_2_link\"/>\n    <origin\
  \ rpy=\"1.5722928534 0 5.41797589164e-06\" xyz=\"9.13566112809e-05 -0.0853218541233\
  \ -0.000127686520102\"/>\n    <axis xyz=\"0 0 1\"/>\n    <limit effort=\"54.0\"\
  \ lower=\"-6.28318530718\" upper=\"6.28318530718\" velocity=\"6.28\"/>\n    <dynamics\
  \ damping=\"0.0\" friction=\"0.0\"/>\n  </joint>\n  <link name=\"wrist_2_link\"\
  >\n    <visual>\n      <origin rpy=\"0 0 0\" xyz=\"0 0 -0.08535\"/>\n      <geometry>\n\
  \        <mesh filename=\"package://ur_e_description/meshes/ur3e/visual/wrist2.dae\"\
  />\n      </geometry>\n      <material name=\"LightGrey\">\n        <color rgba=\"\
  0.7 0.7 0.7 1.0\"/>\n      </material>\n    </visual>\n    <collision>\n      <origin\
  \ rpy=\"0 0 0\" xyz=\"0 0 -0.08535\"/>\n      <geometry>\n        <mesh filename=\"\
  package://ur_e_description/meshes/ur3e/collision/wrist2.stl\"/>\n      </geometry>\n\
  \    </collision>\n    <inertial>\n      <mass value=\"0.8\"/>\n      <origin rpy=\"\
  0 0 0\" xyz=\"0.0 0.0 0.0\"/>\n      <inertia ixx=\"0.00168817023266\" ixy=\"0.0\"\
  \ ixz=\"0.0\" iyy=\"0.00168817023266\" iyz=\"0.0\" izz=\"0.00225\"/>\n    </inertial>\n\
  \  </link>\n  <joint name=\"wrist_3_joint\" type=\"revolute\">\n    <parent link=\"\
  wrist_2_link\"/>\n    <child link=\"wrist_3_link\"/>\n    <origin rpy=\"1.5696887065\
  \ 3.14159265359 3.1415923227\" xyz=\"-0.000204644187552 0.0919106284329 -0.000101802119305\"\
  />\n    <axis xyz=\"0 0 1\"/>\n    <limit effort=\"54.0\" lower=\"-6.28318530718\"\
  \ upper=\"6.28318530718\" velocity=\"6.28\"/>\n    <dynamics damping=\"0.0\" friction=\"\
  0.0\"/>\n  </joint>\n  <link name=\"wrist_3_link\">\n    <visual>\n      <origin\
  \ rpy=\"1.57079632679 0 0\" xyz=\"0 0 -0.0921\"/>\n      <geometry>\n        <mesh\
  \ filename=\"package://ur_e_description/meshes/ur3e/visual/wrist3.dae\"/>\n    \
  \  </geometry>\n      <material name=\"LightGrey\">\n        <color rgba=\"0.7 0.7\
  \ 0.7 1.0\"/>\n      </material>\n    </visual>\n    <collision>\n      <origin\
  \ rpy=\"1.57079632679 0 0\" xyz=\"0 0 -0.0921\"/>\n      <geometry>\n        <mesh\
  \ filename=\"package://ur_e_description/meshes/ur3e/collision/wrist3.stl\"/>\n \
  \     </geometry>\n    </collision>\n    <inertial>\n      <mass value=\"0.35\"\
  />\n      <origin rpy=\"0 0 0\" xyz=\"0.0 0.0 -0.025\"/>\n      <inertia ixx=\"\
  0.000250104066625\" ixy=\"0.0\" ixz=\"0.0\" iyy=\"0.000250104066625\" iyz=\"0.0\"\
  \ izz=\"0.000354375\"/>\n    </inertial>\n  </link>\n  <joint name=\"ee_fixed_joint\"\
  \ type=\"fixed\">\n    <parent link=\"wrist_3_link\"/>\n    <child link=\"ee_link\"\
  />\n    <origin rpy=\"0.0 -1.57079632679 1.57079632679\" xyz=\"0.0 0.0 0.0\"/>\n\
  \  </joint>\n  <link name=\"ee_link\">\n    <collision>\n      <geometry>\n    \
  \    <box size=\"0.01 0.01 0.01\"/>\n      </geometry>\n      <origin rpy=\"0 0\
  \ 0\" xyz=\"-0.01 0 0\"/>\n    </collision>\n  </link>\n  <transmission name=\"\
  shoulder_pan_trans\">\n    <type>transmission_interface/SimpleTransmission</type>\n\
  \    <joint name=\"shoulder_pan_joint\">\n      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>\n\
  \    </joint>\n    <actuator name=\"shoulder_pan_motor\">\n      <mechanicalReduction>1</mechanicalReduction>\n\
  \    </actuator>\n  </transmission>\n  <transmission name=\"shoulder_lift_trans\"\
  >\n    <type>transmission_interface/SimpleTransmission</type>\n    <joint name=\"\
  shoulder_lift_joint\">\n      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>\n\
  \    </joint>\n    <actuator name=\"shoulder_lift_motor\">\n      <mechanicalReduction>1</mechanicalReduction>\n\
  \    </actuator>\n  </transmission>\n  <transmission name=\"elbow_trans\">\n   \
  \ <type>transmission_interface/SimpleTransmission</type>\n    <joint name=\"elbow_joint\"\
  >\n      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>\n\
  \    </joint>\n    <actuator name=\"elbow_motor\">\n      <mechanicalReduction>1</mechanicalReduction>\n\
  \    </actuator>\n  </transmission>\n  <transmission name=\"wrist_1_trans\">\n \
  \   <type>transmission_interface/SimpleTransmission</type>\n    <joint name=\"wrist_1_joint\"\
  >\n      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>\n\
  \    </joint>\n    <actuator name=\"wrist_1_motor\">\n      <mechanicalReduction>1</mechanicalReduction>\n\
  \    </actuator>\n  </transmission>\n  <transmission name=\"wrist_2_trans\">\n \
  \   <type>transmission_interface/SimpleTransmission</type>\n    <joint name=\"wrist_2_joint\"\
  >\n      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>\n\
  \    </joint>\n    <actuator name=\"wrist_2_motor\">\n      <mechanicalReduction>1</mechanicalReduction>\n\
  \    </actuator>\n  </transmission>\n  <transmission name=\"wrist_3_trans\">\n \
  \   <type>transmission_interface/SimpleTransmission</type>\n    <joint name=\"wrist_3_joint\"\
  >\n      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>\n\
  \    </joint>\n    <actuator name=\"wrist_3_motor\">\n      <mechanicalReduction>1</mechanicalReduction>\n\
  \    </actuator>\n  </transmission>\n  <gazebo reference=\"shoulder_link\">\n  \
  \  <selfCollide>true</selfCollide>\n  </gazebo>\n  <gazebo reference=\"upper_arm_link\"\
  >\n    <selfCollide>true</selfCollide>\n  </gazebo>\n  <gazebo reference=\"forearm_link\"\
  >\n    <selfCollide>true</selfCollide>\n  </gazebo>\n  <gazebo reference=\"wrist_1_link\"\
  >\n    <selfCollide>true</selfCollide>\n  </gazebo>\n  <gazebo reference=\"wrist_3_link\"\
  >\n    <selfCollide>true</selfCollide>\n  </gazebo>\n  <gazebo reference=\"wrist_2_link\"\
  >\n    <selfCollide>true</selfCollide>\n  </gazebo>\n  <gazebo reference=\"ee_link\"\
  >\n    <selfCollide>true</selfCollide>\n  </gazebo>\n  <!-- ROS base_link to UR\
  \ 'Base' Coordinates transform -->\n  <link name=\"base\"/>\n  <joint name=\"base_link-base_fixed_joint\"\
  \ type=\"fixed\">\n    <!-- NOTE: this rotation is only needed as long as base_link\
  \ itself is\n                 not corrected wrt the real robot (ie: rotated over\
  \ 180\n                 degrees)\n      -->\n    <origin rpy=\"0 0 -3.14159265359\"\
  \ xyz=\"0 0 0\"/>\n    <parent link=\"base_link\"/>\n    <child link=\"base\"/>\n\
  \  </joint>\n  <!-- Frame coincident with all-zeros TCP on UR controller -->\n \
  \ <link name=\"tool0\"/>\n  <joint name=\"wrist_3_link-tool0_fixed_joint\" type=\"\
  fixed\">\n    <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n    <parent link=\"wrist_3_link\"\
  />\n    <child link=\"tool0\"/>\n  </joint>\n  <link name=\"world\"/>\n  <joint\
  \ name=\"world_joint\" type=\"fixed\">\n    <parent link=\"world\"/>\n    <child\
  \ link=\"base_link\"/>\n    <origin rpy=\"0.0 0.0 0.0\" xyz=\"0.0 0.0 0.0\"/>\n\
  \  </joint>\n</robot>\n"
velocity_limits:
- 3.14
- 3.14
- 3.14
- 6.28
- 6.28
- 6.28
