axis_types:
- [z, y, y, y, z, y]
collision_file_name: collision_ur5.yaml
collision_nn_file: ur5_robotiq_nn
dc_joint_noise: [0, 0, 0, 0, 0, 0]
dc_joint_weight: [0, 0, 0, 0, 0, 0]
disp_offsets:
- [0.0, 0.0, 0.089159]
displacements:
- - [0.0, 0.13585, 0.0]
  - [0.0, -0.1197, 0.425]
  - [0.0, 0.0, 0.39225]
  - [0.0, 0.093, 0.0]
  - [0.0, 0.0, 0.09465]
  - [0.0, 0.0823, 0.0]
ee_fixed_joints: [ee_fixed_joint]
ee_joint_noise: [0.05]
ee_position_weight: [50]
ee_rotation_weight: [49]
fixed_frame: base_link
fixed_frame_noise: 0.0
joint_limits:
- [-6.2831853, 6.2831853]
- [-6.2831853, 6.2831853]
- [-6.2831853, 6.2831853]
- [-6.2831853, 6.2831853]
- [-6.2831853, 6.2831853]
- [-6.2831853, 6.2831853]
joint_names:
- [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint,
  wrist_3_joint]
joint_ordering: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint,
  wrist_2_joint, wrist_3_joint]
joint_state_define_func_file: ur5_robotiq_joint_state_define
joint_types:
- [revolute, revolute, revolute, revolute, revolute, revolute]
match_objectives: []
path_to_src: /home/schoen/Workspaces/lik/src/lively_ik/src
rot_offsets:
- - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 1.570796325]
starting_config: [0, 0, 0, 0, 0, 0]
urdf_file_name: ur5_robotiq.urdf
velocity_limits: [3.15, 3.15, 3.15, 3.2, 3.2, 3.2]
