robot_link_radius: 0.05
sample_states:
- 0.82,0.34,-0.24,-2.32,0.27,2.69,0.10]
training_states: []
problem_states:
- [0.82,0.15,0.32,-3.07,0.52,1.29,0.10]
boxes:
  - name: table
    parameters: [3,3,0.05]
    coordinate_frame: 0
    rotation: [0,0,0]
    translation: [0,0,-0.15]
spheres:
ellipsoids:
capsules:
cylinders:
